version: '3.5'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    hostname: frontend
    ports: [0.0.0.0:8086:8086]
    restart: always
    networks: {inception_network: {ipv4_address: 192.168.99.10}}
    stdin_open: true
    tty: true
    depends_on: ["backend"]

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13.3
#    environment: {POSTGRES_DB: "habrdb", POSTGRES_USER: "habrpguser", POSTGRES_PASSWORD: "pgpwd4habr"}
    env_file: [.env]
    ports: [0.0.0.0:5432:5432]
    volumes: [./db:/var/lib/postgresql/data]
    networks: {inception_network: {ipv4_address: 192.168.99.11}}   

  backend:
    build: ./backend
    container_name: backend
    image: backend
    hostname: backend
    ports: [0.0.0.0:3000:3000]
    restart: always
    networks: {inception_network: {ipv4_address: 192.168.99.12}}
    stdin_open: true
    tty: true
    env_file: [.env]
    depends_on: ["postgres"]    

networks:
  inception_network: {name: ft_transcendence, driver: bridge, ipam: {config: [{subnet: 192.168.99.0/24, gateway: "192.168.99.254"}]}}
